"""adding_foreign_keys_in_courses_registrations

Revision ID: 5b67819ce123
Revises: a500b7d6e22f
Create Date: 2025-06-11 16:05:34.109754

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel
import pydantic

# revision identifiers, used by Alembic.
revision: str = "5b67819ce123"
down_revision: Union[str, None] = "a500b7d6e22f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("courses", schema=None) as batch_op:
        batch_op.alter_column(
            "room_id", existing_type=sa.CHAR(length=32), nullable=True
        )
        batch_op.alter_column(
            "trainer_id", existing_type=sa.CHAR(length=32), nullable=True
        )
        batch_op.create_foreign_key("courses_rooms_id_fk", "rooms", ["room_id"], ["id"])
        batch_op.create_foreign_key(
            "courses_trainers_id_fk", "trainers", ["trainer_id"], ["id"]
        )

    with op.batch_alter_table("rooms", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_rooms_name"), ["name"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rooms", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rooms_name"))

    with op.batch_alter_table("courses", schema=None) as batch_op:
        batch_op.drop_constraint("courses_rooms_id_fk", type_="foreignkey")
        batch_op.drop_constraint("courses_trainers_id_fk", type_="foreignkey")
        batch_op.alter_column(
            "trainer_id", existing_type=sa.CHAR(length=32), nullable=False
        )
        batch_op.alter_column(
            "room_id", existing_type=sa.CHAR(length=32), nullable=False
        )

    # ### end Alembic commands ###
