"""adding_room_color

Revision ID: a500b7d6e22f
Revises: 2425b875fdd2
Create Date: 2025-06-10 16:51:23.009902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel
import pydantic

# revision identifiers, used by Alembic.
revision: str = 'a500b7d6e22f'
down_revision: Union[str, None] = '2425b875fdd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), server_default='white', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
