"""adding_foreign_keys_in_attendances

Revision ID: ab5508a5ed27
Revises: 5b67819ce123
Create Date: 2025-06-11 16:17:10.203074

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel
import pydantic

# revision identifiers, used by Alembic.
revision: str = "ab5508a5ed27"
down_revision: Union[str, None] = "5b67819ce123"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("attendances", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "attendances_courses_id_fk", "courses", ["course_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "attendances_trainees_id_fk", "trainees", ["trainee_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("attendances", schema=None) as batch_op:
        batch_op.drop_constraint("attendances_courses_id_fk", type_="foreignkey")
        batch_op.drop_constraint("attendances_trainees_id_fk", type_="foreignkey")

    # ### end Alembic commands ###
