"""adding_many_to_many_staff_duty

Revision ID: c88f6d6561bb
Revises: ab5508a5ed27
Create Date: 2025-06-11 16:33:46.991690

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel
import pydantic

# revision identifiers, used by Alembic.
revision: str = "c88f6d6561bb"
down_revision: Union[str, None] = "ab5508a5ed27"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "duty_staff_links",
        sa.Column("duty_id", sa.Uuid(), nullable=False),
        sa.Column("staff_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["duty_id"],
            ["duties.id"],
        ),
        sa.ForeignKeyConstraint(
            ["staff_id"],
            ["staff.id"],
        ),
        sa.PrimaryKeyConstraint("duty_id", "staff_id"),
    )
    with op.batch_alter_table("duties", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "title", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
            )
        )
        batch_op.drop_column("staff_id")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("duties", schema=None) as batch_op:
        batch_op.add_column(sa.Column("staff_id", sa.CHAR(length=32), nullable=False))
        batch_op.create_foreign_key("staff_id", "staff", ["staff_id"], ["id"])
        batch_op.drop_column("title")

    op.drop_table("duty_staff_links")
    # ### end Alembic commands ###
